"""baseline schema

Revision ID: 0013a70d0480
Revises:
Create Date: 2026-07-17 10:34:53.359376+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013a70d0480"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute(
        "DO $$ BEGIN CREATE TYPE user_role AS ENUM ('CUSTOMER', 'COURIER', 'ADMIN'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE user_status AS ENUM ('ACTIVE', 'BANNED', 'PENDING_VERIFICATION'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE order_status AS ENUM ('NEW', 'ASSIGNED', 'WAITING_PAYMENT', 'IN_PROGRESS', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'DISPUTED', 'REFUNDED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE invoice_status AS ENUM ('DRAFT', 'ISSUED', 'PAID', 'CANCELLED', 'EXPIRED', 'REFUNDED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE payment_purpose AS ENUM ('ORDER_INVOICE', 'WALLET_TOPUP'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE payment_intent_status AS ENUM ('NEW', 'PAID', 'FAILED', 'EXPIRED', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE payment_method AS ENUM ('WALLET_ONLY', 'GATEWAY_ONLY', 'SPLIT'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE promo_discount_type AS ENUM ('PERCENT', 'FIXED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE promo_redemption_status AS ENUM ('RESERVED', 'CONSUMED', 'RELEASED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE media_type AS ENUM ('CUSTOMER_REQUEST', 'DELIVERY_PROOF'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE message_type AS ENUM ('TEXT', 'IMAGE', 'VIDEO', 'SYSTEM'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE wallet_type AS ENUM ('CUSTOMER', 'COURIER', 'SYSTEM_ESCROW', 'SYSTEM_REVENUE', 'SYSTEM_GATEWAY', 'SYSTEM_TAX_PAYABLE'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE transaction_type AS ENUM ('TOPUP', 'WITHDRAWAL', 'ESCROW_HOLD', 'ESCROW_RELEASE', 'PAYMENT', 'REFUND', 'COMMISSION', 'SERVICE_FEE', 'TAX', 'PROMO_SUBSIDY'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE transaction_status AS ENUM ('PENDING', 'SETTLED', 'REVERSED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE device_os AS ENUM ('IOS', 'ANDROID'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE withdrawal_status AS ENUM ('REQUESTED', 'APPROVED', 'PAID', 'REJECTED'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )
    op.execute(
        "DO $$ BEGIN CREATE TYPE dispute_status AS ENUM ('OPEN', 'RESOLVED_CUSTOMER', 'RESOLVED_COURIER', 'RESOLVED_SPLIT'); EXCEPTION WHEN duplicate_object THEN null; END $$;"
    )

    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN NEW.updated_at = now(); RETURN NEW; END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION enforce_ledger_immutability() RETURNS trigger AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'transactions are append-only: DELETE is forbidden';
          END IF;
          IF OLD.status <> 'PENDING' THEN
            RAISE EXCEPTION 'ledger row is immutable once it is not PENDING';
          END IF;
          IF NEW.status NOT IN ('SETTLED','REVERSED') THEN
            RAISE EXCEPTION 'ledger status may only move PENDING to SETTLED or REVERSED';
          END IF;
          IF NEW.amount <> OLD.amount OR NEW.wallet_id <> OLD.wallet_id
             OR NEW.type <> OLD.type OR NEW.correlation_id <> OLD.correlation_id THEN
            RAISE EXCEPTION 'amount, wallet_id, type, correlation_id are immutable';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION enforce_invoice_item_freeze() RETURNS trigger AS $$
        DECLARE inv_status invoice_status;
        BEGIN
          SELECT status INTO inv_status FROM invoices
            WHERE id = COALESCE(NEW.invoice_id, OLD.invoice_id);
          IF inv_status IS NULL THEN
            RETURN COALESCE(NEW, OLD);  -- parent gone (cascade); nothing to freeze
          END IF;
          IF inv_status <> 'DRAFT' THEN
            RAISE EXCEPTION 'invoice items may only change while the invoice is DRAFT';
          END IF;
          RETURN COALESCE(NEW, OLD);
        END; $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION enforce_message_append_only() RETURNS trigger AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'messages are append-only: DELETE is forbidden';
          END IF;
          IF NEW.conversation_id <> OLD.conversation_id OR NEW.sender_id <> OLD.sender_id
             OR NEW.message_type <> OLD.message_type
             OR NEW.content_encrypted <> OLD.content_encrypted
             OR NEW.created_at <> OLD.created_at THEN
            RAISE EXCEPTION 'messages are immutable except is_read/read_at';
          END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)
    op.create_table(
        "otp_attempts",
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("was_successful", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=120), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM("CUSTOMER", "COURIER", "ADMIN", name="user_role", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE", "BANNED", "PENDING_VERIFICATION", name="user_status", create_type=False
            ),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column(
            "rating",
            sa.Numeric(precision=2, scale=1),
            server_default=sa.text("5.0"),
            nullable=False,
        ),
        sa.Column("rating_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 0.0 AND 5.0", name="chk_rating_range"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone", name="uq_users_phone"),
    )
    op.create_index("idx_users_role_status", "users", ["role", "status"], unique=False)
    op.create_index(
        "uq_users_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "admin_sessions",
        sa.Column("admin_user_id", sa.UUID(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["admin_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token_hash", name="uq_admin_sessions_token_hash"),
    )
    op.create_index(
        "idx_admin_sessions_admin_expires",
        "admin_sessions",
        ["admin_user_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_logs_actor_created",
        "audit_logs",
        ["actor_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "courier_portfolios",
        sa.Column("courier_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column(
            "media_type",
            postgresql.ENUM(
                "TEXT", "IMAGE", "VIDEO", "SYSTEM", name="message_type", create_type=False
            ),
            server_default="IMAGE",
            nullable=False,
        ),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["courier_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_courier_portfolios_courier",
        "courier_portfolios",
        ["courier_id", "display_order"],
        unique=False,
    )
    op.create_table(
        "courier_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("passport_id_encrypted", sa.String(length=512), nullable=True),
        sa.Column("national_id_encrypted", sa.String(length=512), nullable=True),
        sa.Column("identity_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("city_of_residence", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by_admin_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "passport_id_encrypted IS NOT NULL OR national_id_encrypted IS NOT NULL",
            name="chk_identity_present",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["verified_by_admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        "idx_courier_profiles_city_verified",
        "courier_profiles",
        ["city_of_residence", "is_verified"],
        unique=False,
    )
    op.create_index(
        "uq_courier_identity_fingerprint",
        "courier_profiles",
        ["identity_fingerprint"],
        unique=True,
        postgresql_where=sa.text("identity_fingerprint IS NOT NULL"),
    )
    op.create_table(
        "device_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "device_os",
            postgresql.ENUM("IOS", "ANDROID", name="device_os", create_type=False),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=512), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_device_tokens_token"),
    )
    op.create_index("idx_device_tokens_user", "device_tokens", ["user_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("courier_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("delivery_city", sa.String(length=100), nullable=False),
        sa.Column(
            "delivery_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("delivery_address_note", sa.String(length=255), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "NEW",
                "ASSIGNED",
                "WAITING_PAYMENT",
                "IN_PROGRESS",
                "DELIVERED",
                "COMPLETED",
                "CANCELLED",
                "DISPUTED",
                "REFUNDED",
                name="order_status",
                create_type=False,
            ),
            server_default="NEW",
            nullable=False,
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "commission_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "courier_payout_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_date >= CURRENT_DATE AND delivery_date <= CURRENT_DATE + INTERVAL '180 days'",
            name="chk_delivery_date_window",
        ),
        sa.CheckConstraint(
            "status IN ('NEW','CANCELLED') OR courier_id IS NOT NULL",
            name="chk_courier_required_after_assignment",
        ),
        sa.CheckConstraint(
            "total_amount >= 0 AND commission_amount >= 0 AND courier_payout_amount >= 0",
            name="chk_amounts_non_negative",
        ),
        sa.ForeignKeyConstraint(["courier_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["customer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_orders_city_status", "orders", ["delivery_city", "status"], unique=False)
    op.create_index(
        "idx_orders_courier_created",
        "orders",
        ["courier_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("courier_id IS NOT NULL"),
    )
    op.create_index(
        "idx_orders_customer_created",
        "orders",
        ["customer_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_orders_location_gist",
        "orders",
        ["delivery_location"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_orders_status_delivered_at",
        "orders",
        ["status", "delivered_at"],
        unique=False,
        postgresql_where=sa.text("status = 'DELIVERED'"),
    )
    op.create_table(
        "promos",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column(
            "discount_type",
            postgresql.ENUM("PERCENT", "FIXED", name="promo_discount_type", create_type=False),
            nullable=False,
        ),
        sa.Column("percent_value", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("fixed_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("max_discount_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "min_order_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("max_total_usages", sa.Integer(), nullable=True),
        sa.Column("max_usages_per_user", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("used_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(discount_type='PERCENT' AND percent_value IS NOT NULL AND fixed_amount IS NULL AND percent_value > 0 AND percent_value <= 100) OR (discount_type='FIXED' AND fixed_amount IS NOT NULL AND percent_value IS NULL AND fixed_amount > 0)",
            name="chk_promo_value_by_type",
        ),
        sa.CheckConstraint("char_length(code) BETWEEN 3 AND 32", name="chk_promo_code_len"),
        sa.CheckConstraint(
            "code = upper(code) AND code = btrim(code)", name="chk_promo_code_upper"
        ),
        sa.CheckConstraint(
            "starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at", name="chk_promo_window"
        ),
        sa.CheckConstraint(
            "used_count >= 0 AND (max_total_usages IS NULL OR used_count <= max_total_usages) AND max_usages_per_user >= 1",
            name="chk_promo_usage_bounds",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_promos_code"),
    )
    op.create_index(
        "idx_promos_active_window", "promos", ["is_active", "starts_at", "ends_at"], unique=False
    )
    op.create_table(
        "wallets",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "CUSTOMER",
                "COURIER",
                "SYSTEM_ESCROW",
                "SYSTEM_REVENUE",
                "SYSTEM_GATEWAY",
                "SYSTEM_TAX_PAYABLE",
                name="wallet_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "balance",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "held_balance",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'SAR'"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type IN ('CUSTOMER','COURIER') AND user_id IS NOT NULL) OR (type IN ('SYSTEM_ESCROW','SYSTEM_REVENUE','SYSTEM_GATEWAY','SYSTEM_TAX_PAYABLE') AND user_id IS NULL)",
            name="chk_user_wallet_pairing",
        ),
        sa.CheckConstraint(
            "type IN ('SYSTEM_GATEWAY','SYSTEM_REVENUE') OR (balance >= 0 AND held_balance >= 0)",
            name="chk_balance_non_negative",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_wallets_one_escrow",
        "wallets",
        ["type"],
        unique=True,
        postgresql_where=sa.text("type='SYSTEM_ESCROW'"),
    )
    op.create_index(
        "uq_wallets_one_gateway",
        "wallets",
        ["type"],
        unique=True,
        postgresql_where=sa.text("type='SYSTEM_GATEWAY'"),
    )
    op.create_index(
        "uq_wallets_one_revenue",
        "wallets",
        ["type"],
        unique=True,
        postgresql_where=sa.text("type='SYSTEM_REVENUE'"),
    )
    op.create_index(
        "uq_wallets_one_tax",
        "wallets",
        ["type"],
        unique=True,
        postgresql_where=sa.text("type='SYSTEM_TAX_PAYABLE'"),
    )
    op.create_index(
        "uq_wallets_user",
        "wallets",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "conversations",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("courier_id", sa.UUID(), nullable=False),
        sa.Column("last_message_preview_encrypted", sa.String(length=512), nullable=True),
        sa.Column(
            "last_message_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "customer_unread_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "courier_unread_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("is_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", name="uq_conversations_order"),
    )
    op.create_index(
        "idx_conversations_courier_inbox",
        "conversations",
        ["courier_id", sa.literal_column("last_message_timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "idx_conversations_customer_inbox",
        "conversations",
        ["customer_id", sa.literal_column("last_message_timestamp DESC")],
        unique=False,
    )
    op.create_table(
        "disputes",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("raised_by_user_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "OPEN",
                "RESOLVED_CUSTOMER",
                "RESOLVED_COURIER",
                "RESOLVED_SPLIT",
                name="dispute_status",
                create_type=False,
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("resolved_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raised_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", name="uq_disputes_order"),
    )
    op.create_index(
        "idx_disputes_status_created", "disputes", ["status", "created_at"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("issued_by_courier_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT",
                "ISSUED",
                "PAID",
                "CANCELLED",
                "EXPIRED",
                "REFUNDED",
                name="invoice_status",
                create_type=False,
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'SAR'"), nullable=False),
        sa.Column(
            "items_net_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "courier_fee_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "service_fee_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "net_after_discount_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("promo_id", sa.UUID(), nullable=True),
        sa.Column("promo_code_snapshot", sa.String(length=32), nullable=True),
        sa.Column(
            "payment_method",
            postgresql.ENUM(
                "WALLET_ONLY", "GATEWAY_ONLY", "SPLIT", name="payment_method", create_type=False
            ),
            nullable=True,
        ),
        sa.Column(
            "amount_from_wallet",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "amount_from_gateway",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("pricing_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("receipt_email_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'DRAFT' OR total_amount > 0", name="chk_invoice_total_positive"
        ),
        sa.CheckConstraint(
            "(promo_id IS NULL AND discount_amount = 0) OR (promo_id IS NOT NULL AND discount_amount > 0)",
            name="chk_invoice_promo_pairing",
        ),
        sa.CheckConstraint(
            "items_net_amount >= 0 AND courier_fee_amount >= 0 AND service_fee_amount >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0",
            name="chk_invoice_amounts_non_negative",
        ),
        sa.CheckConstraint(
            "net_after_discount_amount = items_net_amount + courier_fee_amount + service_fee_amount - discount_amount",
            name="chk_invoice_net_math",
        ),
        sa.CheckConstraint(
            "total_amount = net_after_discount_amount + tax_amount", name="chk_invoice_total_math"
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_courier_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["promo_id"], ["promos.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_invoices_order", "invoices", ["order_id"], unique=False)
    op.create_index(
        "idx_invoices_promo",
        "invoices",
        ["promo_id"],
        unique=False,
        postgresql_where=sa.text("promo_id IS NOT NULL"),
    )
    op.create_index(
        "idx_invoices_receipt_pending",
        "invoices",
        ["id"],
        unique=False,
        postgresql_where=sa.text("status='PAID' AND receipt_email_sent_at IS NULL"),
    )
    op.create_index(
        "idx_invoices_status_expires",
        "invoices",
        ["status", "expires_at"],
        unique=False,
        postgresql_where=sa.text("status='ISSUED'"),
    )
    op.create_index(
        "uq_invoices_one_active_per_order",
        "invoices",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('DRAFT','ISSUED','PAID')"),
    )
    op.create_table(
        "order_media",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "media_type",
            postgresql.ENUM(
                "CUSTOMER_REQUEST", "DELIVERY_PROOF", name="media_type", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "capture_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "media_type <> 'DELIVERY_PROOF' OR capture_location IS NOT NULL",
            name="chk_proof_has_location",
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_order_media_order_type", "order_media", ["order_id", "media_type"], unique=False
    )
    op.create_table(
        "ratings",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("rater_id", sa.UUID(), nullable=False),
        sa.Column("rated_user_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rater_id <> rated_user_id", name="chk_no_self_rating"),
        sa.CheckConstraint("score BETWEEN 1 AND 5", name="chk_score_range"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["rated_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rater_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "rater_id", name="uq_ratings_order_rater"),
    )
    op.create_index("idx_ratings_rated_user", "ratings", ["rated_user_id"], unique=False)
    op.create_table(
        "withdrawals",
        sa.Column("courier_id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("iban_encrypted", sa.String(length=512), nullable=False),
        sa.Column("iban_last4", sa.String(length=4), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "REQUESTED",
                "APPROVED",
                "PAID",
                "REJECTED",
                name="withdrawal_status",
                create_type=False,
            ),
            server_default="REQUESTED",
            nullable=False,
        ),
        sa.Column("processed_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 50.00", name="chk_withdrawal_min"),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_withdrawals_courier_status", "withdrawals", ["courier_id", "status"], unique=False
    )
    op.create_index(
        "idx_withdrawals_status_created", "withdrawals", ["status", "created_at"], unique=False
    )
    op.create_table(
        "invoice_items",
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("unit_price_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("line_net_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "line_discount_amount",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column("line_taxable_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_net_amount = unit_price_amount * quantity AND line_taxable_amount = line_net_amount - line_discount_amount AND line_total_amount = line_taxable_amount + line_tax_amount",
            name="chk_item_line_math",
        ),
        sa.CheckConstraint("quantity BETWEEN 1 AND 999", name="chk_item_quantity"),
        sa.CheckConstraint("tax_rate >= 0 AND tax_rate <= 1", name="chk_item_tax_rate"),
        sa.CheckConstraint("unit_price_amount > 0", name="chk_item_unit_price"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id", "position", name="uq_invoice_item_position"),
    )
    op.create_index(
        "idx_invoice_items_invoice", "invoice_items", ["invoice_id", "position"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column(
            "message_type",
            postgresql.ENUM(
                "TEXT", "IMAGE", "VIDEO", "SYSTEM", name="message_type", create_type=False
            ),
            server_default="TEXT",
            nullable=False,
        ),
        sa.Column("content_encrypted", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_messages_conversation_keyset",
        "messages",
        ["conversation_id", sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "payment_intents",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "purpose",
            postgresql.ENUM(
                "ORDER_INVOICE", "WALLET_TOPUP", name="payment_purpose", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'SAR'"), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "NEW",
                "PAID",
                "FAILED",
                "EXPIRED",
                "CANCELLED",
                name="payment_intent_status",
                create_type=False,
            ),
            server_default="NEW",
            nullable=False,
        ),
        sa.Column("paylink_transaction_no", sa.String(length=100), nullable=True),
        sa.Column("paylink_url", sa.String(length=512), nullable=True),
        sa.Column("reference_invoice_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(purpose='ORDER_INVOICE' AND reference_invoice_id IS NOT NULL) OR (purpose='WALLET_TOPUP' AND reference_invoice_id IS NULL)",
            name="chk_intent_purpose_reference",
        ),
        sa.CheckConstraint("amount > 0", name="chk_intent_amount_positive"),
        sa.ForeignKeyConstraint(
            ["reference_invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_payment_intents_invoice",
        "payment_intents",
        ["reference_invoice_id"],
        unique=False,
        postgresql_where=sa.text("reference_invoice_id IS NOT NULL"),
    )
    op.create_index(
        "idx_payment_intents_status_expires",
        "payment_intents",
        ["status", "expires_at"],
        unique=False,
        postgresql_where=sa.text("status='NEW'"),
    )
    op.create_index(
        "idx_payment_intents_user_created",
        "payment_intents",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_payment_intents_paylink_txn",
        "payment_intents",
        ["paylink_transaction_no"],
        unique=True,
        postgresql_where=sa.text("paylink_transaction_no IS NOT NULL"),
    )
    op.create_table(
        "promo_redemptions",
        sa.Column("promo_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "RESERVED",
                "CONSUMED",
                "RELEASED",
                name="promo_redemption_status",
                create_type=False,
            ),
            server_default="RESERVED",
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("discount_amount > 0", name="chk_redemption_amount_positive"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(["promo_id"], ["promos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("promo_id", "invoice_id", name="uq_promo_redemption_invoice"),
    )
    op.create_index(
        "idx_promo_redemptions_invoice", "promo_redemptions", ["invoice_id"], unique=False
    )
    op.create_index(
        "idx_promo_redemptions_promo_user",
        "promo_redemptions",
        ["promo_id", "user_id", "status"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "TOPUP",
                "WITHDRAWAL",
                "ESCROW_HOLD",
                "ESCROW_RELEASE",
                "PAYMENT",
                "REFUND",
                "COMMISSION",
                "SERVICE_FEE",
                "TAX",
                "PROMO_SUBSIDY",
                name="transaction_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "SETTLED", "REVERSED", name="transaction_status", create_type=False
            ),
            server_default="SETTLED",
            nullable=False,
        ),
        sa.Column("reference_order_id", sa.UUID(), nullable=True),
        sa.Column("reference_invoice_id", sa.UUID(), nullable=True),
        sa.Column("reference_intent_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount <> 0", name="chk_amount_non_zero"),
        sa.ForeignKeyConstraint(
            ["reference_intent_id"], ["payment_intents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["reference_invoice_id"], ["invoices.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reference_order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transactions_correlation", "transactions", ["correlation_id"], unique=False
    )
    op.create_index(
        "idx_transactions_order",
        "transactions",
        ["reference_order_id"],
        unique=False,
        postgresql_where=sa.text("reference_order_id IS NOT NULL"),
    )
    op.create_index(
        "idx_transactions_wallet_created",
        "transactions",
        ["wallet_id", sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "uq_transactions_idempotency",
        "transactions",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "wallet_topups",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("payment_intent_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 100.00 AND amount <= 20000.00", name="chk_topup_bounds"),
        sa.ForeignKeyConstraint(
            ["payment_intent_id"],
            ["payment_intents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_intent_id", name="uq_wallet_topups_intent"),
    )
    op.create_index(
        "idx_wallet_topups_user_created",
        "wallet_topups",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.execute(
        "CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_courier_profiles_updated_at BEFORE UPDATE ON courier_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_courier_portfolios_updated_at BEFORE UPDATE ON courier_portfolios FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_device_tokens_updated_at BEFORE UPDATE ON device_tokens FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_order_media_updated_at BEFORE UPDATE ON order_media FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_promos_updated_at BEFORE UPDATE ON promos FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_invoices_updated_at BEFORE UPDATE ON invoices FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_invoice_items_updated_at BEFORE UPDATE ON invoice_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_promo_redemptions_updated_at BEFORE UPDATE ON promo_redemptions FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_payment_intents_updated_at BEFORE UPDATE ON payment_intents FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_wallet_topups_updated_at BEFORE UPDATE ON wallet_topups FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_messages_updated_at BEFORE UPDATE ON messages FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_wallets_updated_at BEFORE UPDATE ON wallets FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_transactions_updated_at BEFORE UPDATE ON transactions FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_withdrawals_updated_at BEFORE UPDATE ON withdrawals FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_ratings_updated_at BEFORE UPDATE ON ratings FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_disputes_updated_at BEFORE UPDATE ON disputes FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_admin_sessions_updated_at BEFORE UPDATE ON admin_sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_otp_attempts_updated_at BEFORE UPDATE ON otp_attempts FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_audit_logs_updated_at BEFORE UPDATE ON audit_logs FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    op.execute(
        "CREATE TRIGGER trg_transactions_immutable BEFORE UPDATE OR DELETE ON transactions FOR EACH ROW EXECUTE FUNCTION enforce_ledger_immutability();"
    )
    op.execute(
        "CREATE TRIGGER trg_invoice_items_freeze BEFORE INSERT OR UPDATE OR DELETE ON invoice_items FOR EACH ROW EXECUTE FUNCTION enforce_invoice_item_freeze();"
    )
    op.execute(
        "CREATE TRIGGER trg_messages_append_only BEFORE UPDATE OR DELETE ON messages FOR EACH ROW EXECUTE FUNCTION enforce_message_append_only();"
    )
    op.execute("""
        INSERT INTO wallets (id, type, user_id, balance, held_balance, currency, version)
        VALUES (gen_random_uuid(),'SYSTEM_ESCROW',NULL,0,0,'SAR',0),
               (gen_random_uuid(),'SYSTEM_REVENUE',NULL,0,0,'SAR',0),
               (gen_random_uuid(),'SYSTEM_GATEWAY',NULL,0,0,'SAR',0),
               (gen_random_uuid(),'SYSTEM_TAX_PAYABLE',NULL,0,0,'SAR',0);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_wallet_topups_user_created", table_name="wallet_topups")
    op.drop_table("wallet_topups")
    op.drop_index(
        "uq_transactions_idempotency",
        table_name="transactions",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("idx_transactions_wallet_created", table_name="transactions")
    op.drop_index(
        "idx_transactions_order",
        table_name="transactions",
        postgresql_where=sa.text("reference_order_id IS NOT NULL"),
    )
    op.drop_index("idx_transactions_correlation", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("idx_promo_redemptions_promo_user", table_name="promo_redemptions")
    op.drop_index("idx_promo_redemptions_invoice", table_name="promo_redemptions")
    op.drop_table("promo_redemptions")
    op.drop_index(
        "uq_payment_intents_paylink_txn",
        table_name="payment_intents",
        postgresql_where=sa.text("paylink_transaction_no IS NOT NULL"),
    )
    op.drop_index("idx_payment_intents_user_created", table_name="payment_intents")
    op.drop_index(
        "idx_payment_intents_status_expires",
        table_name="payment_intents",
        postgresql_where=sa.text("status='NEW'"),
    )
    op.drop_index(
        "idx_payment_intents_invoice",
        table_name="payment_intents",
        postgresql_where=sa.text("reference_invoice_id IS NOT NULL"),
    )
    op.drop_table("payment_intents")
    op.drop_index("idx_messages_conversation_keyset", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_invoice_items_invoice", table_name="invoice_items")
    op.drop_table("invoice_items")
    op.drop_index("idx_withdrawals_status_created", table_name="withdrawals")
    op.drop_index("idx_withdrawals_courier_status", table_name="withdrawals")
    op.drop_table("withdrawals")
    op.drop_index("idx_ratings_rated_user", table_name="ratings")
    op.drop_table("ratings")
    op.drop_index("idx_order_media_order_type", table_name="order_media")
    op.drop_table("order_media")
    op.drop_index(
        "uq_invoices_one_active_per_order",
        table_name="invoices",
        postgresql_where=sa.text("status IN ('DRAFT','ISSUED','PAID')"),
    )
    op.drop_index(
        "idx_invoices_status_expires",
        table_name="invoices",
        postgresql_where=sa.text("status='ISSUED'"),
    )
    op.drop_index(
        "idx_invoices_receipt_pending",
        table_name="invoices",
        postgresql_where=sa.text("status='PAID' AND receipt_email_sent_at IS NULL"),
    )
    op.drop_index(
        "idx_invoices_promo",
        table_name="invoices",
        postgresql_where=sa.text("promo_id IS NOT NULL"),
    )
    op.drop_index("idx_invoices_order", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index("idx_disputes_status_created", table_name="disputes")
    op.drop_table("disputes")
    op.drop_index("idx_conversations_customer_inbox", table_name="conversations")
    op.drop_index("idx_conversations_courier_inbox", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(
        "uq_wallets_user", table_name="wallets", postgresql_where=sa.text("user_id IS NOT NULL")
    )
    op.drop_index(
        "uq_wallets_one_tax",
        table_name="wallets",
        postgresql_where=sa.text("type='SYSTEM_TAX_PAYABLE'"),
    )
    op.drop_index(
        "uq_wallets_one_revenue",
        table_name="wallets",
        postgresql_where=sa.text("type='SYSTEM_REVENUE'"),
    )
    op.drop_index(
        "uq_wallets_one_gateway",
        table_name="wallets",
        postgresql_where=sa.text("type='SYSTEM_GATEWAY'"),
    )
    op.drop_index(
        "uq_wallets_one_escrow",
        table_name="wallets",
        postgresql_where=sa.text("type='SYSTEM_ESCROW'"),
    )
    op.drop_table("wallets")
    op.drop_index("idx_promos_active_window", table_name="promos")
    op.drop_table("promos")
    op.drop_index(
        "idx_orders_status_delivered_at",
        table_name="orders",
        postgresql_where=sa.text("status = 'DELIVERED'"),
    )
    op.drop_index("idx_orders_location_gist", table_name="orders", postgresql_using="gist")
    op.drop_index("idx_orders_customer_created", table_name="orders")
    op.drop_index(
        "idx_orders_courier_created",
        table_name="orders",
        postgresql_where=sa.text("courier_id IS NOT NULL"),
    )
    op.drop_index("idx_orders_city_status", table_name="orders")
    op.drop_table("orders")
    op.drop_index("idx_device_tokens_user", table_name="device_tokens")
    op.drop_table("device_tokens")
    op.drop_index(
        "uq_courier_identity_fingerprint",
        table_name="courier_profiles",
        postgresql_where=sa.text("identity_fingerprint IS NOT NULL"),
    )
    op.drop_index("idx_courier_profiles_city_verified", table_name="courier_profiles")
    op.drop_table("courier_profiles")
    op.drop_index("idx_courier_portfolios_courier", table_name="courier_portfolios")
    op.drop_table("courier_portfolios")
    op.drop_index("idx_audit_logs_entity", table_name="audit_logs")
    op.drop_index("idx_audit_logs_actor_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("idx_admin_sessions_admin_expires", table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_index(
        "uq_users_email", table_name="users", postgresql_where=sa.text("email IS NOT NULL")
    )
    op.drop_index("idx_users_role_status", table_name="users")
    op.drop_table("users")
    op.drop_table("otp_attempts")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.execute("DROP FUNCTION IF EXISTS enforce_ledger_immutability()")
    op.execute("DROP FUNCTION IF EXISTS enforce_invoice_item_freeze()")
    op.execute("DROP FUNCTION IF EXISTS enforce_message_append_only()")
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS user_status")
    op.execute("DROP TYPE IF EXISTS order_status")
    op.execute("DROP TYPE IF EXISTS invoice_status")
    op.execute("DROP TYPE IF EXISTS payment_purpose")
    op.execute("DROP TYPE IF EXISTS payment_intent_status")
    op.execute("DROP TYPE IF EXISTS payment_method")
    op.execute("DROP TYPE IF EXISTS promo_discount_type")
    op.execute("DROP TYPE IF EXISTS promo_redemption_status")
    op.execute("DROP TYPE IF EXISTS media_type")
    op.execute("DROP TYPE IF EXISTS message_type")
    op.execute("DROP TYPE IF EXISTS wallet_type")
    op.execute("DROP TYPE IF EXISTS transaction_type")
    op.execute("DROP TYPE IF EXISTS transaction_status")
    op.execute("DROP TYPE IF EXISTS device_os")
    op.execute("DROP TYPE IF EXISTS withdrawal_status")
    op.execute("DROP TYPE IF EXISTS dispute_status")
    # ### end Alembic commands ###
